name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change to your branch name if different
  pull_request:
    branches:
      - main # Change to your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0" # Specify the PHP version you are using

      - name: Install Composer dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit # Adjust if you're using a different testing framework

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' # Only deploy on pushes to main branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Server
        run: |
          ssh user@yourserver.com 'cd /path/to/your/project && git pull origin main'
