name: CI/CD Pipeline

on:
  push:
    branches:
      - main # Change to your branch name if different
  pull_request:
    branches:
      - main # Change to your branch name if different

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.0" # Specify the PHP version you are using

      - name: Install Composer dependencies
        run: composer install

      - name: Run tests
        run: vendor/bin/phpunit # Adjust if you're using a different testing framework


  # You can add a deploy job here if you decide to use another deployment method later
